# Generated by Django 3.2.4 on 2021-06-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210627_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='nom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
