# Generated by Django 3.2.4 on 2021-06-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_tag_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsocial',
            name='image',
            field=models.ImageField(upload_to='static/store/image/uploads/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/store/image/uploads/'),
        ),
    ]
