# Generated by Django 3.2.4 on 2021-06-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210628_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsocial',
            name='ajouter_le',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='postsocial',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
