# Generated by Django 3.2.4 on 2021-07-02 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210630_1421'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostSocial',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='client',
        ),
        migrations.AddField(
            model_name='commande',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='commande',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.produit'),
        ),
    ]
