# Generated by Django 3.2.5 on 2021-07-03 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210702_1023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commande',
        ),
    ]
