# Generated by Django 3.2.5 on 2021-07-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20210716_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='default_invoicing_address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='default_shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_charge_id',
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(max_length=80, null=True, verbose_name='Address de livraison'),
        ),
    ]
