# Generated by Django 3.2.5 on 2021-07-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20210723_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('W', 'En attente de validation'), ('P', 'Commande confirmée'), ('P', "En cours d'expedition"), ('S', 'Expédiée'), ('C', 'Annulée')], default='W', max_length=1, verbose_name='Statut de la commande'),
        ),
    ]
