# Generated by Django 3.2.5 on 2021-07-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('En attente de validation', 'En attente de validation'), ('Commande confirmée', 'Commande confirmée'), ("En cours d'expedition", "En cours d'expedition"), ('Livrée', 'Livrée'), ('Annulée', 'Annulée')], default='En attente de validation', max_length=50, verbose_name='Statut de la commande'),
        ),
    ]
