# Generated by Django 3.2.5 on 2021-07-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(default='nul', max_length=40, verbose_name='Address du client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('Monsieur', 'Monsieur'), ('Mademoiselle', 'Mademoiselle'), ('Madame', 'Madame')], default='Monsieur', max_length=20, verbose_name='Civilité'),
        ),
        migrations.AddField(
            model_name='client',
            name='mobile',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
