# Generated by Django 3.2.5 on 2021-07-25 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_remove_order_shipping_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commande', to='store.order', verbose_name='Commande associée'),
        ),
    ]
